# Generated by Django 4.0 on 2023-09-25 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvupload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label_group',
            name='mt_idx',
        ),
        migrations.RemoveField(
            model_name='label_tag',
            name='mt_idx',
        ),
    ]
