# Generated by Django 4.0 on 2023-09-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvupload', '0002_remove_label_group_mt_idx_remove_label_tag_mt_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_table',
            name='name',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
