# Generated by Django 4.0 on 2023-09-26 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csvupload', '0003_main_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_table',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='csvupload.label_group'),
        ),
        migrations.AlterField(
            model_name='main_table',
            name='maj_tag_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='MajorTag', to='csvupload.label_tag'),
        ),
        migrations.AlterField(
            model_name='main_table',
            name='min_tag_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='MinorTag', to='csvupload.label_tag'),
        ),
    ]
