# Generated by Django 4.0 on 2023-09-26 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csvupload', '0004_alter_main_table_group_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label_group',
            options={'verbose_name': 'Group'},
        ),
        migrations.AlterModelOptions(
            name='label_tag',
            options={'verbose_name': 'Tag'},
        ),
        migrations.AlterModelOptions(
            name='main_table',
            options={'verbose_name': 'Table'},
        ),
        migrations.AddField(
            model_name='main_table',
            name='meta_details',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='main_table',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='GroupTag', to='csvupload.label_group'),
        ),
        migrations.AlterField(
            model_name='main_table',
            name='maj_tag_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='MajorTag', to='csvupload.label_tag'),
        ),
        migrations.AlterField(
            model_name='main_table',
            name='min_tag_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='MinorTag', to='csvupload.label_tag'),
        ),
    ]
