# Generated by Django 4.0 on 2023-09-27 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvupload', '0006_main_table_alis_name_alter_main_table_group_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_table',
            old_name='alis_name',
            new_name='alias_name',
        ),
    ]
